name: dxartist
description:  Design is everything!

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl:	/
url: 
permalink: /:year/:month/:title/
owner:
    name: dxartist
    twitter: sharathdt
    github: dxartist
    disqus_shortname: dxartist

ga_id:  UA-57202838-1 
ga_username: dxartist

timezone: 
