name: nadjetey
markdown: redcarpet
pygments: true
url: http://nadjetey.github.io
permalink: /:year/:month/:title/
owner:
    name: Nii Adjetey Sowah
    twitter: _nadjetey
    github: nadjetey
    disqus_shortname: nadjetey

ga_id: UA-48177899-1
ga_username: nadjetey.github.io

timezone: Africa/Accra