name: nadjetey's blog
description:  My corner of the web

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://nadjetey.github.io
permalink: /:year/:month/:title/
owner:
    name: Nii Adjetey Sowah
    twitter: _nadjetey
    github: nadjetey
    disqus_shortname: nadjetey

ga_id: UA-48177899-1
ga_username: nadjetey.github.io

timezone: Africa/Accra